[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:uvicorn]
command=python -m uvicorn app.main:app --uds /tmp/uvicorn.sock --log-level info --proxy-headers
directory=/app
environment=PYTHONPATH="/app",DISABLE_CLOUD_LOGGING="false",GRPC_ENABLE_FORK_SUPPORT="0",GRPC_POLL_STRATEGY="poll",GRPC_DNS_RESOLVER="native",GRPC_VERBOSITY="ERROR"
autostart=true
autorestart=true
startsecs=5
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
