"""Added glossary and eligibility models

Revision ID: 99de00e32082
Revises: 3559b534283a
Create Date: 2026-04-22 19:05:16.110781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '99de00e32082'
down_revision: Union[str, Sequence[str], None] = '3559b534283a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eligibilityrule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rule_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expected_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explanation_if_failed', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glossaryitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('definition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('example', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glossaryitem_term'), 'glossaryitem', ['term'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_glossaryitem_term'), table_name='glossaryitem')
    op.drop_table('glossaryitem')
    op.drop_table('eligibilityrule')
    # ### end Alembic commands ###
